juttle/juttle-client-library

- CHANGELOG.md
- example/index.html
- example/index.js
- src/utils/job-socket.js
- src/view/index.js
- src/view/sink.js
- Shuffled `job-socket` around so we're no longer inheriting from `EventEmitter`
- Fixed bug with rerunning a View that would cause points from separate jobs to get merged.
@go-oleg @davidvgalbraith
> Job event woes

- example/example.juttle
- example/index.js
- example/webpack.config.js
- package.json
Hilariously ran into this issue when trying to run a juttle program that had string interpolation. Found it conflicted with es6's groovy string interplation, when js complained about not finding a var in the program.
@go-oleg
> Load juttle in example from external file

- src/view/reducers.js
Fixes juttle/outrigger#83
When running a different program from our original program, there
was an issue with the old views getting reinstantiated because they
still existed in redux store. This change resets the views in the store
to an empty object so new views are only instantiated when we have info
about them.
> Clear views array on job_create event

- src/view/view.js
Was seeing some weird console log messages because we were not
unsubscribing from jobEvents and destroying the componentChart when the
view unmounted.
@go-oleg
> Better Clean for unmounting views

- sass/main.scss
If the `.css` extension is there, then it ends up being transformed into `url()` css which is not what we want, we want it to be bundled into the build juttle-client-library css file.
http://stackoverflow.com/a/30279590/2359560
@mnibecker
> fix how react-select css is imported

- package.json
Bumping juttle-viz version to get the regression fix in https://github.com/juttle/juttle-viz/pull/32
cc @rlgomes @mnibecker @mstemm
> bump juttle-viz version to 0.3.1

- example/index.html
- example/index.js
- src/utils/job-socket.js
- src/view/actions.js
- src/view/index.js
- src/view/reducers.js
add `view.clear()` which stops the current job and resets views.
also fixed bug I found with stopping and starting a view not working (should probably add a unit test for this)
> Views clear fn

- .babelrc
- example/.babelrc
- example/webpack.config.js
- package.json
- sass/main.scss
- src/inputs/components/input-types/duration-input.js
- src/inputs/components/input-types/index.js
- test/inputs/components/duration.spec.js
Add duration input.
The duration input is a little different from the other inputs in that it internally maintains a special representation of the current value so that we can limit how much we change its UI component values. For example, if a user increments from 59 minutes to 60 minutes, we want to keep showing the 60 minutes instead of 1 hour (which we would otherwise show when converting a `moment.duration` to its "best" number and unit representation).
Also added a couple small changes to babelrc and webpack config (see individual commits).
@mnibecker @davidvgalbraith
> inputs: adding duration input

- src/utils/error-messages.js
- src/view/juttle-view-gen.js
- test/views/juttle-view-gen.spec.js
Previously we were reporting very general errors for multiple views.
Instead throw error at first instantiated view error and render
detailed information.
@go-oleg
> Juttle view errors 2

- example/index.js
- src/inputs/actions.js
- src/inputs/components/input-types/number-input.js
- src/inputs/components/input-types/text-input.js
- src/inputs/index.js
- src/inputs/reducers.js
- test/inputs/actions.spec.js
As part of working on this, discovered there was a race condition between when a user updates the value of an input and the value returned from `inputs.getValues()` (see first commit for details).
@mnibecker
> change input.getValues to return a promise and text/number input to update onBlur

- src/inputs/input-group.js
This feature wasn't plumbed through the juttle-client-library public API.
Removing instead of fixing because this is an application-level feature thats better implemented in the juttle-client-library consumer.
@mnibecker @davidvgalbraith
> inputs: remove run via shift+enter functionality

- src/inputs/components/input-types/number-input.js
- src/inputs/components/input-types/text-input.js
With this change, hitting enter when focused on a text or number input submits its value to the store (i.e. has the same effect as blurring). This is convenient because hitting **enter** is a typical cue that a user is done with editing the value. The other somewhat _coupled_ (and not the most elegant) reason is that when a user hits **enter**, we want to make sure the value is submitted before rerunning the juttle program in https://github.com/juttle/juttle-viewer/pull/20.
@mnibecker
> text and number input: submit value when enter is pressed

- example/index.js
- src/view/index.js
Was needed in order for rendering runtime errors in juttle-viewer. Why
not make the View class inherit `event-target` and provide the ability
to listen to all events.
@go-oleg
> Subscribe to job events in view

- package.json
- test/utils/job-manager.spec.js
There was an issue with the previous version that required a hack in the
socket-manager test. The release of 2.0.0 has fixed this issue.
Also, removed immutable from package.json (it wasn't being used).
@go-oleg
> Bump version of mock-socket

- src/index.js
```
export default function Juttle ...
```
wasn't getting properly converted by [babel-plugin-add-module-exports](https://github.com/59naga/babel-plugin-add-module-exports/) to work with commonjs `require()`.
The change here makes it work. Didn't look into if this a bug in `babel-plugin-add-module-exports` because this feels nicer anyways.
@mnibecker
> fix export in src/index.js so it works properly with commonjs

- sass/main.scss
- src/utils/job-manager.js
- src/view/index.js
- src/view/juttle-view-gen.js
- src/view/view-layout-gen.js
- src/view/view-layout.js
- src/view/view.js
- test/utils/job-manager.spec.js
- test/views/juttle-view-gen.spec.js
- test/views/view-layout-gen.spec.js
To match changes made in https://github.com/juttle/juttle-service/pull/47.
Also modify a couple other places where the term 'sink' was used.
@mnibecker 
(will merge once a version of juttle-service containing https://github.com/juttle/juttle-service/pull/47 is published)
> expect websocket messages to contain view* instead of sink* properties

- CHANGELOG.md
- package.json
- src/utils/job-manager.js
- src/view/index.js
- test/utils/job-manager.spec.js
When the readyState of the internal WebSocket changes, fire job-status
event. Hook this event to the view class so users can subscribe to it as
well. Event returns the JobStatus code of the job (0= CONNECTING,
1= OPEN, etc)
Arose from a need in juttle-viewer to keep track of the status of a
running job. Now we have it.
@go-oleg
> job-manager: job-status events

- webpack.config.js
based on https://webpack.github.io/docs/webpack-for-browserify-users.html#standalone
@mnibecker
> webpack: fix umd config to export as library as JuttleClientLibrary

- CHANGELOG.md
- src/utils/job-manager.js
- test/utils/job-manager.spec.js
Was experiencing this issue when trying to implement a better run button
on juttle-viewer. Currently we await the server to issue a close event,
and as a result was reporting the job as running (for several seconds), when it really had
recieved a `job_end` event.
It's better for the job-manager to close itself and immediately
get set to `STOPPED` state.
@go-oleg @VladVega @davidvgalbraith
> Close websocket on job_end event

- src/utils/http-api.js
- src/utils/job-manager.js
- src/views/index.js
- test/utils/http-api.spec.js
Adding debug log support.
One question is: should there be tests associated with this? I didn't find anything similar (there is successful call to runJob tested) so I thought I'd ask.
Notice the conflict: 
It's weird because the tests pass still. I noticed that when I make these same changes (happens without conflict) to master instead of `v0.6.0` there is an error when running the `juttle-engine-client`
> add: debug log support

- package.json
- sass/main.scss
- src/inputs/components/input-types/date-input.js
Necessary so we can localize the datepicker styles to the inputs' DOM instead of the whole DOM. 
This became an issue in https://github.com/juttle/atom-juttle-viewer/pull/1 where some of the date picker styling was affecting atom's tabs.
- Had to bump the datepicker version to get support for this. The date display format changed so explicitly configuring it to what we had (YYYY-MM-DD).
- Not a huge fan of the `componentDidMount`/`setState` pattern to get the DOM node after the first render, but don't know of a better way to achieve this.
@mnibecker
> date input: tether component popup to date input component instead of body

- README.md
Add an ecosystem section to each README to show its part in the
overall architecture.
Also this README was empty, so add a minimal Introduction section that
copies the brief description from the ecosystem page.
@go-oleg @mnibecker
> Add ecosystem link to juttle-client-library.

- src/inputs/input-transformers.js
- src/inputs/reducers.js
- test/inputs/input-transformers.spec.js
- test/inputs/reducers.spec.js
Resolves https://github.com/juttle/juttle-client-library/issues/75.
Tried to implement this in a somewhat generic/extendible way so we can add other transformers/processors/normalizers later. This code may eventually move to the juttle layer via https://github.com/juttle/juttle/issues/148.
Couldn't come up with a better name than the generic term "transformers".
@mnibecker
> input -items option: allow array of strings
