package.json

Switch to npm version of juttle-viz

---

.eslintignore
.eslintrc
.travis.yml
README.md
example/index.js
package.json
src/index.js
src/inputs/actions.js
src/inputs/components/input-container.js
src/inputs/components/input-types.js
src/inputs/index.js
src/inputs/input-group.js
src/inputs/reducers.js
src/utils/api.js
src/utils/job-socket.js
src/view/actions.js
src/view/index.js
src/view/reducers.js
src/view/sink-layout-gen.js
src/view/sink-registry.js
src/view/sink.js
src/view/view-layout.js

Inspired heavily by rackt's eslint setup: https://github.com/rackt/eslint-config-rackt/blob/master/index.js
A couple of highlights:
- requires use of double quotes for strings
- require semicolons
- In switch statements cases should not be indented.

Add eslint and travis

---

src/inputs/input-group.js

@mnibecker (the outrigger equivalent was done here https://github.com/juttle/outrigger/pull/34)

lint fix: add missing semicolon

---

package.json
sass/main.scss
src/inputs/components/input-types/index.js
src/inputs/components/input-types/select-input.js

implemented as a thin wrapper around https://github.com/JedWatson/react-select
@mnibecker

inputs: add "select" input type

---

package.json
sass/main.scss
src/inputs/components/input-container.js
src/inputs/components/input-types.js
src/inputs/components/input-types/index.js
src/inputs/components/input-types/number-input.js
src/inputs/components/input-types/select-input.js
src/inputs/components/input-types/text-input.js

(also moves the `label` used by each input into `input-container`)
@mnibecker

move inputs into separate files

---

CHANGELOG.md

changelog: update for 0.1.6 release

---

.eslintrc
example/index.js
src/errors/actions.js
src/errors/error-view.js
src/errors/index.js
src/errors/reducers.js
src/index.js
src/inputs/actions.js
src/inputs/components/input-container.js
src/inputs/components/input-types/index.js
src/inputs/components/input-types/number-input.js
src/inputs/components/input-types/select-input.js
src/inputs/components/input-types/text-input.js
src/inputs/index.js
src/inputs/input-group.js
src/inputs/reducers.js
src/utils/api.js
src/utils/job-socket.js
src/view/actions.js
src/view/index.js
src/view/reducers.js
src/view/view-layout-gen.js
src/view/view-layout.js
src/view/view-registry.js
src/view/view.js
test/inputs/actions.spec.js
test/utils/job-socket.spec.js
test/views/view-layout-gen.spec.js

single quote enforcement

---

package.json
sass/main.scss
src/inputs/components/input-types/date-input.js
src/inputs/components/input-types/index.js

add date input

---

CHANGELOG.md

Also, go through previous changelog items and linkify the PRs.
cc @mnibecker

changelog: Add items going into the next release.

---

CHANGELOG.md

changelog: change Next release to 0.2.0

---

CHANGELOG.md

cc @mnibecker @rlgomes @mstemm

changelog: update for 0.2.1 release

---

.eslintrc
package.json

eslint: imports should come before other code

---

example/index.html
example/index.js
src/errors/actions.js
src/errors/index.js
src/errors/reducers.js

Errors clear

---

example/index.html
example/index.js
src/inputs/actions.js
src/inputs/index.js
src/inputs/reducers.js

Inputs clear

---

src/inputs/components/input-types/index.js
src/inputs/components/input-types/multiselect-input.js

inputs: add multiselect input

---

package.json
sass/main.scss

bump juttle-viz to 0.4.0

---

CHANGELOG.md

CHANGELOG: update for 0.4.0

---

src/utils/error-messages.js
src/view/juttle-view-gen.js
test/views/juttle-view-gen.spec.js

Reverts juttle/juttle-client-library#42

Revert "Juttle view errors 2"

---

src/index.js
src/inputs/actions.js
src/inputs/index.js
src/inputs/reducers.js
src/view/index.js
test/inputs/actions.spec.js

Resolves https://github.com/juttle/juttle-client-library/issues/52.
@mnibecker

change 'outrigger' references to 'juttle service'

---

src/inputs/components/input-types/date-input.js
test/inputs/components/input-types/date.spec.js
test/inputs/components/input-types/duration.spec.js

Fixes https://github.com/juttle/juttle-viewer/issues/27.
@mnibecker

date input: display time in utc

---

package.json

package.json: bump juttle-jsdp to 0.3.0

---

package.json

package.json: bump juttle-viz to 0.5.0

---

CHANGELOG.md

Changelog 0.6.0

---

package.json
src/utils/http-api.js
test/utils/http-api.spec.js

Catch address not found errors in isomorphic-fetch.
@go-oleg

Address not found error

---

CHANGELOG.md
package.json
src/utils/http-api.js
test/utils/http-api.spec.js

backport of #65 
cc @mnibecker

Backport PR 65

---

src/views/view.js

@go-oleg you helped me with this.

Fix offsetWidth undefined error

---

src/index.js
src/utils/job-manager.js
test/utils/job-manager.spec.js
test/views/index.spec.js

Export job-manager and statuses

---

package.json
src/views/view-registry.js

Bump juttle viz add markdown view

---

package.json
src/inputs/actions.js
test/inputs/actions.spec.js

Fixes https://github.com/juttle/juttle-engine/issues/88.
@mnibecker @davidvgalbraith

updateInputValue: fix handling of situation when value hasn't changed

---

.babelrc
package.json

Like https://github.com/juttle/juttle-viewer/pull/56 but for Juttle Client Library.
@rlgomes

babel: add Object.assign transform to support older browsers

---

CHANGELOG.md

CHANGELOG: update for 0.7.1

---

package.json
src/utils/job-manager.js
src/views/index.js
src/views/juttle-view-gen.js
src/views/view-registry.js
src/views/view.js
test/views/juttle-view-gen.spec.js

@VladVega @davidvgalbraith 
Will change `juttle-viz` to the non-rc release once its published.

Prepare 0.8.0
